language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: AjvTPdaTPEMGgODjx6bgRUry+tptiTOvSGqJVwqZb1WU3yaqxLmp75nS4ZmH2/yegehLUii8+s9Pt4jpfrSCiDZfUQoej++EB7aElXBsDYteVNkJz+qZK5/UScojtgaY3eLh7SfY2NLnHegqBg3Bx0RTJ5YA08SCTKaroLC+Jt8=
  - secure: ItFvEKPg9iF/dNhQ9wJ08MGR25UJpGtFBGImdf+VADagpLiJbyGb71oSC3ZfFj6DRjAS+YhRO658IQK9DDjxtK5ubtsyzQqk76cpD/ayiD3Dm8H/P8qpHQ7e0Yeuxh3/UF3f6yUdJYXJQR0yL8tVPUXDNwR4Zv/2jE7qFoOTpLw=
  matrix:
  - BROWSER_NAME=chrome BROWSER_VERSION=latest
  - BROWSER_NAME=chrome BROWSER_VERSION=29
  - BROWSER_NAME=firefox BROWSER_VERSION=latest
  - BROWSER_NAME=opera BROWSER_VERSION=latest
  - BROWSER_NAME=safari BROWSER_VERSION=latest
  - BROWSER_NAME=safari BROWSER_VERSION=7
  - BROWSER_NAME=safari BROWSER_VERSION=6
  - BROWSER_NAME=safari BROWSER_VERSION=5
  - BROWSER_NAME=ie BROWSER_VERSION=11
  - BROWSER_NAME=ie BROWSER_VERSION=10
  - BROWSER_NAME=ie BROWSER_VERSION=9
